version: '3.7'

services:
  basic:
    image: basic
    environment:
      - "PYTHONUNBUFFERED=1"
      - QT_X11_NO_MITSHM=1
      - DISPLAY=$DISPLAY
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"     
    privileged: true
    tty: true
    stdin_open: true
    command: python test.py
