version: '3.7'

services:
  basic:
    image: basic
    environment:
      - QT_X11_NO_MITSHM=1
      - DISPLAY=$DISPLAY
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"     
    command: python test.py
